version: "3.9"
services:
  postgresql:
    image: postgres
    env_file:
      - database.env
    ports:
      - "3333:5432"
  myapp:
    build: .
    ports:
      - "8888:8080"
    environment:
      WAIT_HOSTS: postgresql:5432
      WAIT_TIMEOUT: 900
      POSTGRES_HOST: postgresql
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
